import math
phi=(1+5**0.5)/2
fourpi=4*math.pi*math.sqrt(2)
print("== is 4pi sqrt2 ~ phi^6 a coincidence, or icosahedral pi-phi structure? ==")
print(f"  4pi sqrt2 = {fourpi:.4f}")
print(f"  phi^6     = {phi**6:.4f}   (= 8 phi + 5, Fibonacci)")
print(f"  ratio phi^6/(4pi sqrt2) = {phi**6/fourpi:.5f}  ({(phi**6/fourpi-1)*100:+.2f}%)")
print()
print("  KEY: phi and pi ARE exactly linked in icosahedral geometry: phi = 2 cos(pi/5).")
c36=math.cos(math.pi/5)
print(f"    2 cos(pi/5) = {2*c36:.6f} = phi  (EXACT identity)")
print(f"    so phi^6 = (2cos(pi/5))^6 = 64 cos^6(pi/5) = {64*c36**6:.4f}")
print(f"    but 4pi sqrt2 = {fourpi:.4f}  -> phi^6 != 4pi sqrt2 (differ {(phi**6/fourpi-1)*100:.1f}%).")
print("  => the icosahedral link makes pi-phi coincidences RECUR, but does NOT force THIS one.")
print("     A derived structural identity would be EXACT; the 1% gap says near-coincidence.")
print()
print("== BONUS BUG found while checking: eq:MPl is internally inconsistent ==")
print("  Paper: M_Pl^2 = Lam_UV^2/(32 pi^2)  AND  Lam_UV = M_Pl/(4 pi sqrt2).")
print("  Invert the first: Lam_UV = sqrt(32 pi^2) M_Pl = 4 pi sqrt2 M_Pl = %.2f M_Pl (SUPER-Planckian)."%fourpi)
print("  The stated Lam_UV = M_Pl/(4pi sqrt2) = %.4f M_Pl is the RECIPROCAL."%(1/fourpi))
print("  Check: if Lam_UV=M_Pl/(4pi sqrt2), then Lam_UV^2/(32pi^2)=M_Pl^2/(32pi^2)^2 != M_Pl^2.")
print("  => either M_Pl^2 = Lam_UV^2/(32pi^2) (then Lam_UV ~ 17.8 M_Pl ~ phi^6 M_Pl, super-Planckian),")
print("     or Lam_UV = M_Pl/(4pi sqrt2) (then the relation must read M_Pl^2 = 32pi^2 Lam_UV^2).")
print("  Standard induced gravity (M_Pl below the cutoff) favours Lam_UV = 4pi sqrt2 M_Pl ~ phi^6 M_Pl.")
print("  Either way the phi^6 COINCIDENCE is unchanged (4pi sqrt2 ~ phi^6); only the DIRECTION flips.")
